dataset_params:
  dataset_path_fixed: 'training_dataset'
  evaluation_path_fixed: 'evaluation_dataset'
  dataset_path: 'training_dataset'
  evaluation_path: 'evaluation_dataset'
  scale_labeled_samples: [.025, .05, .10, .20]

metric_model_params:
  number_of_neurons_1: 32
  number_of_neurons_2: 64
  in_channels: 8

metric_exp_params:
  batch_size: 32
  epochs: 50
  LR: 0.001
  number_pos_neg: 5

regression_model_params:
  number_of_neurons_1: 512
  number_of_neurons_2: 1024
  number_of_neurons_3: 512
  in_channels: 64

regression_exp_params:
  batch_size: 32
  epochs: 100
  LR: 0.001
  optimizer: 'adam'
  # category: 'metric'
  category: 'normal'

experiment_params:
  base_data_dir: 'data'
  run_iter: 50

logging_params:
  save_dir: 'saves/'
  manual_seed: 2333
