dataset_params:
  dataset_path_fixed: "training_dataset"
  evaluation_path_fixed: "evaluation_dataset"
  dataset_path: "training_dataset"
  evaluation_path: "evaluation_dataset"
  scale_labeled_samples: [0.005, .025, .05]
  # scale_labeled_samples: [.025, .05, .1, .2]

model_params:
  number_of_neurons_1: 16
  number_of_neurons_2: 32
  in_channels: 13,
  number_pos_neg: 5

exp_params:
  batch_size: 32
  epochs: 1
  LR: 0.001
  optimizer: "adam"

regression_model_params:
  number_of_neurons_1: 256
  number_of_neurons_2: 512
  number_of_neurons_3: 256
  in_channels: 32

regression_exp_params:
  batch_size: 32
  epochs: 100
  LR: 0.001
  optimizer: 'adam'

logging_params:
  save_dir: "saves/"
  manual_seed: 2333

experiment_params:
  run_iter: 50
  base_data_dir: "data"
  iteration: 3
  tau: 3
  gr: 1
  K: 3
  # s_strategy: 'metric'
  s_strategy: 'normal'